CREATE TABLE IF NOT EXISTS users (id VARCHAR(64) PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(190) NOT NULL UNIQUE,phone VARCHAR(40),password_hash VARCHAR(255) NOT NULL,role ENUM('CUSTOMER','ADMIN') NOT NULL DEFAULT 'CUSTOMER',preferred_language ENUM('ar','en') NOT NULL DEFAULT 'en',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS categories (id VARCHAR(64) PRIMARY KEY,slug VARCHAR(100) NOT NULL UNIQUE,name_en VARCHAR(120) NOT NULL,name_ar VARCHAR(120) NOT NULL,sort_order INT NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS products (id VARCHAR(64) PRIMARY KEY,slug VARCHAR(120) NOT NULL UNIQUE,category_id VARCHAR(64) NOT NULL,name_en VARCHAR(160) NOT NULL,name_ar VARCHAR(160) NOT NULL,description_en VARCHAR(500),description_ar VARCHAR(500),image VARCHAR(255) NOT NULL,base_price DECIMAL(10,2) NOT NULL,type ENUM('drink','pastry') NOT NULL DEFAULT 'drink',is_available BOOLEAN NOT NULL DEFAULT TRUE,sort_order INT NOT NULL DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(category_id) REFERENCES categories(id));
CREATE TABLE IF NOT EXISTS favorites (user_id VARCHAR(64) NOT NULL,product_id VARCHAR(64) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(user_id,product_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS orders (id VARCHAR(64) PRIMARY KEY,order_number VARCHAR(30) NOT NULL UNIQUE,user_id VARCHAR(64),customer_name VARCHAR(120) NOT NULL,customer_phone VARCHAR(40) NOT NULL,notes TEXT,subtotal DECIMAL(10,2) NOT NULL,delivery_fee DECIMAL(10,2) NOT NULL DEFAULT 0,total DECIMAL(10,2) NOT NULL,status ENUM('NEW','CONFIRMED','PREPARING','READY','OUT_FOR_DELIVERY','COMPLETED','CANCELLED') NOT NULL DEFAULT 'NEW',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS order_items (id VARCHAR(64) PRIMARY KEY,order_id VARCHAR(64) NOT NULL,product_id VARCHAR(64),product_name VARCHAR(160) NOT NULL,quantity INT NOT NULL,unit_price DECIMAL(10,2) NOT NULL,customization_json JSON,FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS chat_messages (id VARCHAR(64) PRIMARY KEY,user_id VARCHAR(64),session_id VARCHAR(100) NOT NULL,role ENUM('user','assistant') NOT NULL,content TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL);


CREATE TABLE IF NOT EXISTS coupons (
  id VARCHAR(64) PRIMARY KEY,
  code VARCHAR(64) NOT NULL UNIQUE,
  discount_type ENUM('PERCENT','FIXED') NOT NULL,
  discount_value DECIMAL(10,2) NOT NULL,
  minimum_order DECIMAL(10,2) NOT NULL DEFAULT 0,
  maximum_discount DECIMAL(10,2),
  usage_limit INT,
  used_count INT NOT NULL DEFAULT 0,
  starts_at DATETIME,
  expires_at DATETIME,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS reviews (
  id VARCHAR(64) PRIMARY KEY,
  user_id VARCHAR(64),
  product_id VARCHAR(64) NOT NULL,
  rating TINYINT NOT NULL,
  comment VARCHAR(1000),
  status ENUM('PENDING','APPROVED','HIDDEN') NOT NULL DEFAULT 'PENDING',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE,
  INDEX(product_id,status)
);
CREATE TABLE IF NOT EXISTS site_settings (
  setting_key VARCHAR(100) PRIMARY KEY,
  setting_value TEXT,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS audit_logs (
  id VARCHAR(64) PRIMARY KEY,
  admin_user_id VARCHAR(64),
  action VARCHAR(120) NOT NULL,
  entity_type VARCHAR(80),
  entity_id VARCHAR(64),
  metadata_json JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(admin_user_id) REFERENCES users(id) ON DELETE SET NULL,
  INDEX(created_at), INDEX(entity_type,entity_id)
);
