SET NAMES utf8mb4;

INSERT INTO categories
(id, slug, name_en, name_ar, sort_order)
VALUES
('cat-strong', 'strong', 'Strong', 'قهوة قوية', 1),
('cat-milk-based', 'milk-based', 'Milk based', 'قهوة بالحليب', 2),
('cat-sweet', 'sweet', 'Sweet', 'مشروبات حلوة', 3),
('cat-iced', 'iced', 'Iced', 'مشروبات باردة', 4),
('cat-croissants', 'croissants', 'Croissants', 'كرواسون', 5)
ON DUPLICATE KEY UPDATE
name_en = VALUES(name_en),
name_ar = VALUES(name_ar),
sort_order = VALUES(sort_order);

INSERT INTO products
(
  id,
  slug,
  category_id,
  name_en,
  name_ar,
  description_en,
  description_ar,
  image,
  base_price,
  type,
  is_available,
  sort_order
)
VALUES
(
  'espresso',
  'espresso',
  'cat-strong',
  'Espresso',
  'إسبريسو',
  'Dense · cocoa · caramel',
  'كثيف · كاكاو · كراميل',
  '/drinks/Espresso.png',
  80,
  'drink',
  TRUE,
  1
),
(
  'americano',
  'americano',
  'cat-strong',
  'Americano',
  'أمريكانو',
  'Clean · long · aromatic',
  'خفيف · طويل · عطري',
  '/drinks/Americano.png',
  95,
  'drink',
  TRUE,
  2
),
(
  'latte',
  'latte',
  'cat-milk-based',
  'Latte',
  'لاتيه',
  'Silky · gentle · balanced',
  'ناعم · خفيف · متوازن',
  '/drinks/Latte.png',
  120,
  'drink',
  TRUE,
  3
),
(
  'spanish-latte',
  'spanish-latte',
  'cat-sweet',
  'Spanish Latte',
  'سبانش لاتيه',
  'Creamy · condensed · rich',
  'كريمي · حليب مكثف · غني',
  '/drinks/spanish latte hot.png',
  145,
  'drink',
  TRUE,
  4
),
(
  'vanilla-latte',
  'vanilla-latte',
  'cat-sweet',
  'Vanilla Latte',
  'فانيلا لاتيه',
  'Vanilla bean · velvet milk',
  'فانيلا · حليب مخملي',
  '/drinks/Vanilla Latte.png',
  140,
  'drink',
  TRUE,
  5
),
(
  'caramel-macchiato',
  'caramel-macchiato',
  'cat-sweet',
  'Caramel Macchiato',
  'كراميل ماكياتو',
  'Caramel · espresso · creamy milk',
  'كراميل · إسبريسو · حليب كريمي',
  '/drinks/Caramel Macchiato.png',
  145,
  'drink',
  TRUE,
  6
),
(
  'flat-white',
  'flat-white',
  'cat-milk-based',
  'Flat White',
  'فلات وايت',
  'Microfoam · strong finish',
  'رغوة ناعمة · مذاق قوي',
  '/drinks/Flat White.png',
  125,
  'drink',
  TRUE,
  7
),
(
  'cappuccino',
  'cappuccino',
  'cat-milk-based',
  'Cappuccino',
  'كابتشينو',
  'Airy · cocoa dust · classic',
  'رغوي · كاكاو · كلاسيك',
  '/drinks/Cappuccino.png',
  120,
  'drink',
  TRUE,
  8
),
(
  'mocha',
  'mocha',
  'cat-sweet',
  'Mocha',
  'موكا',
  'Dark chocolate · espresso',
  'شوكولاتة داكنة · إسبريسو',
  '/drinks/Mocha.png',
  145,
  'drink',
  TRUE,
  9
),
(
  'cold-brew',
  'cold-brew',
  'cat-iced',
  'Cold Brew',
  'كولد برو',
  '18-hour steep · smooth',
  'تحضير 18 ساعة · ناعم',
  '/drinks/Cold Brew.png',
  135,
  'drink',
  TRUE,
  10
),
(
  'affogato',
  'affogato',
  'cat-sweet',
  'Affogato',
  'أفوجاتو',
  'Vanilla gelato · hot espresso',
  'جيلاتو فانيلا · إسبريسو ساخن',
  '/drinks/Affogato.png',
  155,
  'drink',
  TRUE,
  11
),
(
  'white-mocha',
  'white-mocha',
  'cat-sweet',
  'White Mocha',
  'وايت موكا',
  'White chocolate · espresso · velvet milk',
  'شوكولاتة بيضاء · إسبريسو · حليب مخملي',
  '/drinks/White Mocha.png',
  155,
  'drink',
  TRUE,
  12
),
(
  'plain-croissant',
  'plain-croissant',
  'cat-croissants',
  'Plain Croissant',
  'كرواسون سادة',
  'Buttery · flaky · freshly baked',
  'زبدة · مورق · طازج',
  '/pastries/plain-croissant.png',
  60,
  'pastry',
  TRUE,
  13
),
(
  'chocolate-croissant',
  'chocolate-croissant',
  'cat-croissants',
  'Chocolate Croissant',
  'كرواسون شوكولاتة',
  'Dark chocolate · crisp golden layers',
  'شوكولاتة داكنة · طبقات مقرمشة',
  '/pastries/chocolate-croissant.png',
  85,
  'pastry',
  TRUE,
  14
),
(
  'almond-croissant',
  'almond-croissant',
  'cat-croissants',
  'Almond Croissant',
  'كرواسون لوز',
  'Almond cream · toasted almond flakes',
  'كريمة لوز · شرائح لوز محمصة',
  '/pastries/almond-croissant.png',
  95,
  'pastry',
  TRUE,
  15
),
(
  'pistachio-croissant',
  'pistachio-croissant',
  'cat-croissants',
  'Pistachio Croissant',
  'كرواسون فستق',
  'Pistachio cream · roasted pistachios',
  'كريمة فستق · فستق محمص',
  '/pastries/pistachio-croissant.png',
  110,
  'pastry',
  TRUE,
  16
),
(
  'cheese-croissant',
  'cheese-croissant',
  'cat-croissants',
  'Cheese Croissant',
  'كرواسون جبنة',
  'Warm cheese · buttery pastry',
  'جبنة دافئة · عجينة بالزبدة',
  '/pastries/cheese-croissant.png',
  80,
  'pastry',
  TRUE,
  17
),
(
  'turkey-cheese-croissant',
  'turkey-cheese-croissant',
  'cat-croissants',
  'Turkey & Cheese Croissant',
  'كرواسون تركي وجبنة',
  'Turkey · melted cheese · flaky crust',
  'تركي · جبنة ذائبة · عجينة مورقة',
  '/pastries/turkey-cheese-croissant.png',
  120,
  'pastry',
  TRUE,
  18
)
ON DUPLICATE KEY UPDATE
category_id = VALUES(category_id),
name_en = VALUES(name_en),
name_ar = VALUES(name_ar),
description_en = VALUES(description_en),
description_ar = VALUES(description_ar),
image = VALUES(image),
base_price = VALUES(base_price),
type = VALUES(type),
is_available = VALUES(is_available),
sort_order = VALUES(sort_order);