"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { BarChart3, Boxes, Coffee, FolderKanban, LogOut, Package, Pencil, Plus, RefreshCw, Search, TicketPercent, Trash2, Users, X } from "lucide-react";

type Tab="dashboard"|"products"|"orders"|"customers"|"coupons"|"categories";
type OrderStatus="NEW"|"CONFIRMED"|"PREPARING"|"READY"|"OUT_FOR_DELIVERY"|"COMPLETED"|"CANCELLED";
const statuses:OrderStatus[]=["NEW","CONFIRMED","PREPARING","READY","OUT_FOR_DELIVERY","COMPLETED","CANCELLED"];
const nav:[Tab,string,any][]=[["dashboard","Dashboard",BarChart3],["products","Products",Boxes],["orders","Orders",Package],["customers","Customers",Users],["coupons","Coupons",TicketPercent],["categories","Categories",FolderKanban]];
const money=(v:any)=>`${Number(v||0).toFixed(0)} EGP`;

export default function AdminDashboard(){
 const [tab,setTab]=useState<Tab>("dashboard"),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState("");
 const [stats,setStats]=useState<any>({summary:{},bestSelling:[]}),[orders,setOrders]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]),[categories,setCategories]=useState<any[]>([]),[customers,setCustomers]=useState<any[]>([]),[coupons,setCoupons]=useState<any[]>([]);
 const [modal,setModal]=useState<null|{kind:"product"|"category"|"coupon",item?:any}>(null);
 const api=useCallback(async(url:string,options?:RequestInit)=>{const r=await fetch(url,{cache:"no-store",...options,headers:{"Content-Type":"application/json",...(options?.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Request failed");return d},[]);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const [s,o,p,c,u,cp]=await Promise.all([api("/api/admin/stats"),api("/api/admin/orders"),api("/api/admin/products"),api("/api/admin/categories"),api("/api/admin/customers"),api("/api/admin/coupons")]);setStats(s);setOrders(o.orders||[]);setProducts(p.products||[]);setCategories(c.categories||[]);setCustomers(u.customers||[]);setCoupons(cp.coupons||[])}catch(e){setError(e instanceof Error?e.message:"Could not load dashboard")}finally{setLoading(false)}},[api]);
 useEffect(()=>{fetch("/api/auth/me",{cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error();const d=await r.json();if(d?.user?.role!=="ADMIN")location.href="/login";else load()}).catch(()=>location.href="/login")},[load]);
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});location.href="/"}
 async function updateOrder(id:string,status:OrderStatus){await api(`/api/admin/orders/${id}`,{method:"PATCH",body:JSON.stringify({status})});setOrders(v=>v.map(o=>o.id===id?{...o,status}:o));load()}
 async function remove(kind:string,id:string){if(!confirm("Are you sure?"))return;await api(`/api/admin/${kind}/${id}`,{method:"DELETE"});load()}
 const filtered=useMemo(()=>{const q=query.toLowerCase();const source=tab==="products"?products:tab==="orders"?orders:tab==="customers"?customers:tab==="coupons"?coupons:tab==="categories"?categories:[];return !q?source:source.filter((x:any)=>JSON.stringify(x).toLowerCase().includes(q))},[tab,query,products,orders,customers,coupons,categories]);
 return <main className="min-h-screen bg-[#fbf7f2] text-[#42271b]">
  <div className="grid min-h-screen lg:grid-cols-[250px_1fr]">
   <aside className="border-b border-[#6b4635]/10 bg-white px-4 py-4 sm:px-5 lg:sticky lg:top-0 lg:h-screen lg:border-b-0 lg:border-r lg:py-7">
    <a href="/" className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-full bg-[#4a2a1a] text-white"><Coffee size={20}/></span><span><strong className="block font-serif text-2xl">NØIR Admin</strong><small className="text-[#a06f54]">Store management</small></span></a>
    <div className="mt-4 rounded-2xl border border-[#6b4635]/10 p-3 lg:mt-7 lg:p-4"><strong>Riham Admin</strong><p className="mt-1 text-xs text-[#a06f54]">NØIR BEAN Owner</p></div>
    <nav className="mt-5 flex gap-2 overflow-x-auto pb-2 lg:mt-8 lg:block lg:space-y-2 lg:overflow-visible lg:pb-0">{nav.map(([id,label,Icon])=><button key={id} onClick={()=>{setTab(id);setQuery("")}} className={`flex shrink-0 items-center gap-2 rounded-2xl px-4 py-3 text-left text-sm transition lg:w-full lg:gap-3 ${tab===id?"bg-[#ead8c6] text-[#3d2116]":"hover:bg-[#f6eee7]"}`}><Icon size={18}/>{label}</button>)}</nav>
    <button onClick={logout} className="mt-3 flex items-center gap-3 rounded-2xl px-4 py-3 text-sm text-red-800 hover:bg-red-50 lg:mt-8 lg:w-full"><LogOut size={18}/>Log out</button>
   </aside>
   <section className="min-w-0 p-4 sm:p-5 md:p-9 lg:p-12">
    <header className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="text-[10px] uppercase tracking-[.36em] text-[#bd7f58]">NØIR control room</p><h1 className="mt-2 font-serif text-4xl capitalize sm:text-5xl md:text-6xl">{tab}.</h1><p className="mt-2 text-sm text-[#8d6651]">Manage the café from one clean workspace.</p></div><div className="flex flex-wrap gap-3"><button onClick={load} className="flex items-center gap-2 rounded-full border border-[#5a3624]/15 bg-white px-5 py-3 text-sm"><RefreshCw size={16} className={loading?"animate-spin":""}/>Refresh</button>{["products","categories","coupons"].includes(tab)&&<button onClick={()=>setModal({kind:tab.slice(0,-1) as any})} className="flex items-center gap-2 rounded-full bg-[#4a2a1a] px-5 py-3 text-sm text-white"><Plus size={16}/>Add {tab.slice(0,-1)}</button>}</div></header>
    {error&&<div className="mt-6 rounded-2xl bg-red-50 p-4 text-red-800">{error}</div>}
    {tab!=="dashboard"&&<div className="mt-7 flex max-w-xl items-center gap-3 rounded-full border border-[#5a3624]/10 bg-white px-5 py-3"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${tab}...`} className="w-full bg-transparent text-sm outline-none"/></div>}
    {tab==="dashboard"&&<Dashboard stats={stats} orders={orders} products={products} customers={customers}/>} 
    {tab==="products"&&<Products items={filtered} onEdit={item=>setModal({kind:"product",item})} onDelete={id=>remove("products",id)}/>} 
    {tab==="orders"&&<Orders items={filtered} updateOrder={updateOrder}/>} 
    {tab==="customers"&&<Customers items={filtered}/>} 
    {tab==="coupons"&&<Coupons items={filtered} onEdit={item=>setModal({kind:"coupon",item})} onDelete={id=>remove("coupons",id)}/>} 
    {tab==="categories"&&<Categories items={filtered} onEdit={item=>setModal({kind:"category",item})} onDelete={id=>remove("categories",id)}/>} 
   </section>
  </div>
  {modal&&<Editor modal={modal} categories={categories} api={api} close={()=>setModal(null)} done={()=>{setModal(null);load()}}/>}
 </main>
}
function Card({label,value,sub}:{label:string,value:any,sub?:string}){return <div className="rounded-[28px] border border-[#6c4633]/8 bg-white p-6 shadow-[0_15px_45px_rgba(70,40,25,.06)]"><p className="text-[10px] uppercase tracking-[.22em] text-[#a57459]">{label}</p><strong className="mt-3 block font-serif text-4xl">{value}</strong>{sub&&<p className="mt-2 text-xs text-[#98715c]">{sub}</p>}</div>}
function Dashboard({stats,orders,products,customers}:{stats:any,orders:any[],products:any[],customers:any[]}){const s=stats.summary||{};return <><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card label="Total orders" value={s.totalOrders||0}/><Card label="Completed sales" value={money(s.totalSales)}/><Card label="New orders" value={s.newOrders||0}/><Card label="Customers" value={customers.length}/></div><div className="mt-6 grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><div className="rounded-[30px] bg-white p-6"><h2 className="font-serif text-3xl">Recent orders</h2><div className="mt-5 space-y-3">{orders.slice(0,6).map(o=><div key={o.id} className="flex items-center justify-between rounded-2xl bg-[#f8f0e8] p-4"><div><strong>{o.customerName}</strong><p className="text-xs text-[#9a7059]">{o.orderNumber||o.id} · {o.status}</p></div><strong>{money(o.total)}</strong></div>)}{!orders.length&&<p className="py-12 text-center text-[#9a7059]">No orders yet.</p>}</div></div><div className="rounded-[30px] bg-[#4a2a1a] p-6 text-white"><h2 className="font-serif text-3xl">Best sellers</h2><div className="mt-5 space-y-4">{(stats.bestSelling||[]).map((x:any,i:number)=><div key={x.name} className="flex items-center justify-between border-b border-white/10 pb-4"><span>{i+1}. {x.name}</span><strong>{x.quantity}</strong></div>)}{!(stats.bestSelling||[]).length&&<p className="text-white/60">Sales data will appear here.</p>}</div><p className="mt-8 text-xs text-white/55">{products.length} products currently in the catalog.</p></div></div></>}
function Products({items,onEdit,onDelete}:{items:any[],onEdit:(x:any)=>void,onDelete:(id:string)=>void}){return <div className="mt-7 grid gap-5 sm:grid-cols-2 2xl:grid-cols-3">{items.map(p=><article key={p.id} className="overflow-hidden rounded-[28px] border border-[#6b4635]/8 bg-white"><div className="relative h-[320px] overflow-hidden bg-[#f1dfca] sm:h-80"><img src={p.image} alt={p.name_en || "Product"} className="absolute inset-0 h-full w-full object-contain object-center p-3 sm:p-5"/></div><div className="p-5"><div className="flex justify-between gap-3"><div><p className="text-xs text-[#ad7658]">{p.category_name}</p><h3 className="font-serif text-2xl">{p.name_en}</h3><p className="mt-1 text-sm text-[#8d6651]">{p.name_ar}</p></div><strong>{money(p.base_price)}</strong></div><div className="mt-5 flex justify-between"><span className={`rounded-full px-3 py-1 text-xs ${p.is_available?"bg-green-50 text-green-800":"bg-red-50 text-red-800"}`}>{p.is_available?"Available":"Hidden"}</span><div className="flex gap-2"><button onClick={()=>onEdit(p)} className="rounded-full border p-2"><Pencil size={15}/></button><button onClick={()=>onDelete(p.id)} className="rounded-full border p-2 text-red-700"><Trash2 size={15}/></button></div></div></div></article>)}</div>}
function Orders({items,updateOrder}:{items:any[],updateOrder:(id:string,s:OrderStatus)=>void}){return <div className="mt-7 space-y-4">{items.map(o=><article key={o.id} className="rounded-[28px] bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs text-[#a57459]">{o.orderNumber||o.id}</p><h3 className="font-serif text-3xl">{o.customerName}</h3><p className="text-sm text-[#8d6651]">{o.customerPhone}</p><p className="mt-2 max-w-2xl whitespace-pre-wrap text-sm text-[#684533]"><strong>Address:</strong> {o.address||"—"}</p>{o.notes&&<p className="mt-2 max-w-2xl whitespace-pre-wrap text-sm text-[#8d6651]"><strong>Notes:</strong> {o.notes}</p>}</div><select value={o.status} onChange={e=>updateOrder(o.id,e.target.value as OrderStatus)} className="rounded-full bg-[#4a2a1a] px-4 py-3 text-sm text-white">{statuses.map(s=><option key={s}>{s}</option>)}</select></div><div className="mt-5 grid gap-2">{o.items?.map((x:any,i:number)=><div key={i} className="flex justify-between rounded-2xl bg-[#f8f0e8] p-3 text-sm"><span>{x.quantity}× {x.name} <small className="text-[#9a7059]">{x.size} · {x.temperature} · {x.sugar} · {x.bean}</small></span><strong>{money(x.quantity*x.unitPrice)}</strong></div>)}</div><div className="mt-5 flex justify-between border-t pt-4"><span>{new Date(o.createdAt).toLocaleString()}</span><strong className="font-serif text-2xl">{money(o.total)}</strong></div></article>)}</div>}
function Customers({items}:{items:any[]}){return <div className="mt-7 overflow-hidden rounded-[28px] bg-white"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-[#f2e3d5]"><tr>{["Customer","Phone","Role","Orders","Spent","Joined"].map(x=><th key={x} className="p-4">{x}</th>)}</tr></thead><tbody>{items.map(x=><tr key={x.id} className="border-t"><td className="p-4"><strong>{x.name}</strong><p className="text-xs text-[#9a7059]">{x.email}</p></td><td className="p-4">{x.phone||"—"}</td><td className="p-4">{x.role}</td><td className="p-4">{x.ordersCount}</td><td className="p-4">{money(x.totalSpent)}</td><td className="p-4">{new Date(x.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table></div></div>}
function Categories({items,onEdit,onDelete}:{items:any[],onEdit:(x:any)=>void,onDelete:(id:string)=>void}){return <div className="mt-7 grid gap-5 sm:grid-cols-2 2xl:grid-cols-3">{items.map(x=><article key={x.id} className="rounded-[28px] bg-white p-6"><p className="text-xs uppercase tracking-widest text-[#b57957]">{x.slug}</p><h3 className="mt-2 font-serif text-3xl">{x.nameEn}</h3><p className="mt-1 text-[#9a7059]">{x.nameAr}</p><div className="mt-6 flex justify-end gap-2"><button onClick={()=>onEdit(x)} className="rounded-full border p-2"><Pencil size={15}/></button><button onClick={()=>onDelete(x.id)} className="rounded-full border p-2 text-red-700"><Trash2 size={15}/></button></div></article>)}</div>}
function Coupons({items,onEdit,onDelete}:{items:any[],onEdit:(x:any)=>void,onDelete:(id:string)=>void}){return <div className="mt-7 grid gap-5 sm:grid-cols-2 2xl:grid-cols-3">{items.map(x=><article key={x.id} className="rounded-[28px] bg-white p-6"><div className="flex justify-between"><h3 className="font-serif text-3xl">{x.code}</h3><span className={`rounded-full px-3 py-1 text-xs ${x.isActive?"bg-green-50 text-green-800":"bg-gray-100"}`}>{x.isActive?"Active":"Paused"}</span></div><strong className="mt-5 block text-2xl">{x.discountType==="PERCENT"?`${x.discountValue}%`:money(x.discountValue)}</strong><p className="mt-2 text-sm text-[#9a7059]">Minimum order: {money(x.minimumOrder)} · Used {x.usedCount||0}{x.usageLimit?` / ${x.usageLimit}`:""}</p><div className="mt-6 flex justify-end gap-2"><button onClick={()=>onEdit(x)} className="rounded-full border p-2"><Pencil size={15}/></button><button onClick={()=>onDelete(x.id)} className="rounded-full border p-2 text-red-700"><Trash2 size={15}/></button></div></article>)}</div>}
function Editor({modal,categories,api,close,done}:{modal:any,categories:any[],api:any,close:()=>void,done:()=>void}){const [f,setF]=useState<any>(modal.item||{}),[busy,setBusy]=useState(false),[err,setErr]=useState("");const set=(k:string,v:any)=>setF((x:any)=>({...x,[k]:v}));async function save(){setBusy(true);setErr("");try{let url=`/api/admin/${modal.kind}s`,method="POST",body:any={};if(modal.kind==="category")body={slug:f.slug,nameEn:f.nameEn,nameAr:f.nameAr,sortOrder:Number(f.sortOrder||0)};if(modal.kind==="product")body={slug:f.slug||f.nameEn?.toLowerCase().replace(/[^a-z0-9]+/g,"-"),categoryId:f.categoryId||f.category_id,nameEn:f.nameEn||f.name_en,nameAr:f.nameAr||f.name_ar,descriptionEn:f.descriptionEn??f.description_en??"",descriptionAr:f.descriptionAr??f.description_ar??"",image:f.image,basePrice:Number(f.basePrice??f.base_price),type:f.type||"drink",isAvailable:f.isAvailable??Boolean(f.is_available??true),sortOrder:Number(f.sortOrder??f.sort_order??0)};if(modal.kind==="coupon")body={code:f.code,discountType:f.discountType||"PERCENT",discountValue:Number(f.discountValue||0),minimumOrder:Number(f.minimumOrder||0),maximumDiscount:f.maximumDiscount?Number(f.maximumDiscount):null,usageLimit:f.usageLimit?Number(f.usageLimit):null,startsAt:f.startsAt||null,expiresAt:f.expiresAt||null,isActive:f.isActive??true};if(modal.item){url+=`/${modal.item.id}`;method="PATCH";if(modal.kind==="product")body={nameEn:body.nameEn,nameAr:body.nameAr,descriptionEn:body.descriptionEn,descriptionAr:body.descriptionAr,image:body.image,basePrice:body.basePrice,isAvailable:body.isAvailable,sortOrder:body.sortOrder};if(modal.kind==="category")body={slug:body.slug,nameEn:body.nameEn,nameAr:body.nameAr,sortOrder:body.sortOrder};if(modal.kind==="coupon")body={isActive:body.isActive,discountValue:body.discountValue,minimumOrder:body.minimumOrder,expiresAt:body.expiresAt}}await api(url,{method,body:JSON.stringify(body)});done()}catch(e){setErr(e instanceof Error?e.message:"Could not save")}finally{setBusy(false)}}
 const input=(label:string,key:string,type="text")=><label className="block"><span className="mb-2 block text-xs uppercase tracking-wider text-[#a16e52]">{label}</span><input type={type} value={f[key]??""} onChange={e=>set(key,type==="number"?Number(e.target.value):e.target.value)} className="w-full rounded-2xl border border-[#6b4635]/12 bg-white px-4 py-3 outline-none"/></label>;
 return <div className="fixed inset-0 z-[300] grid place-items-center bg-[#24130c]/60 p-4 backdrop-blur-md"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-[32px] bg-[#fbf5ed] p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-xs uppercase tracking-widest text-[#b27656]">Catalog editor</p><h2 className="font-serif text-4xl">{modal.item?"Edit":"Add"} {modal.kind}</h2></div><button onClick={close} className="grid h-10 w-10 place-items-center rounded-full border"><X/></button></div><div className="mt-6 grid gap-4 md:grid-cols-2">{modal.kind==="category"&&<>{input("Slug","slug")}{input("Sort order","sortOrder","number")}{input("English name","nameEn")}{input("Arabic name","nameAr")}</>}{modal.kind==="product"&&<>{!modal.item&&input("Slug","slug")}<label><span className="mb-2 block text-xs uppercase tracking-wider text-[#a16e52]">Category</span><select value={f.categoryId||f.category_id||""} onChange={e=>set("categoryId",e.target.value)} className="w-full rounded-2xl border bg-white px-4 py-3"><option value="">Select category</option>{categories.map(c=><option value={c.id} key={c.id}>{c.nameEn}</option>)}</select></label>{input("English name",modal.item?"name_en":"nameEn")}{input("Arabic name",modal.item?"name_ar":"nameAr")}{input("Image path","image")}{input("Base price",modal.item?"base_price":"basePrice","number")}<label><span className="mb-2 block text-xs uppercase tracking-wider text-[#a16e52]">Type</span><select value={f.type||"drink"} onChange={e=>set("type",e.target.value)} className="w-full rounded-2xl border bg-white px-4 py-3"><option value="drink">Drink</option><option value="pastry">Pastry</option></select></label>{input("Sort order",modal.item?"sort_order":"sortOrder","number")}</>}{modal.kind==="coupon"&&<>{input("Coupon code","code")}<label><span className="mb-2 block text-xs uppercase tracking-wider text-[#a16e52]">Discount type</span><select value={f.discountType||"PERCENT"} onChange={e=>set("discountType",e.target.value)} className="w-full rounded-2xl border bg-white px-4 py-3"><option>PERCENT</option><option>FIXED</option></select></label>{input("Discount value","discountValue","number")}{input("Minimum order","minimumOrder","number")}{input("Usage limit","usageLimit","number")}{input("Expiry date","expiresAt","datetime-local")}</>}</div><label className="mt-5 flex items-center gap-3"><input type="checkbox" checked={f.isAvailable??f.isActive??Boolean(f.is_available??true)} onChange={e=>set(modal.kind==="coupon"?"isActive":"isAvailable",e.target.checked)}/>Active / available</label>{err&&<p className="mt-4 text-sm text-red-700">{err}</p>}<button onClick={save} disabled={busy} className="mt-6 w-full rounded-full bg-[#4a2a1a] py-4 text-white disabled:opacity-50">{busy?"Saving...":"Save changes"}</button></div></div>}
