"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Eye, EyeOff, UserPlus } from "lucide-react";

export default function RegisterPage(){
 const router=useRouter(); const [show,setShow]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");const f=new FormData(e.currentTarget);const payload={name:f.get("name"),email:f.get("email"),phone:f.get("phone"),password:f.get("password"),language:f.get("language"),adminCode:f.get("adminCode")};const r=await fetch('/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();setLoading(false);if(!r.ok){setError(d.error||'Could not create account');return}window.dispatchEvent(new Event('noir-auth-changed'));router.push(d.user.role==='ADMIN'?'/admin':'/account');router.refresh()}
 return <main className="min-h-screen bg-[radial-gradient(circle_at_top,#ead4b8,#c9986f_38%,#26140c_100%)] text-[#351d12]"><Navbar/><section className="mx-auto flex min-h-screen max-w-6xl items-center justify-center px-5 py-32"><div className="grid w-full overflow-hidden rounded-[42px] border border-white/25 bg-[#f7eadb]/94 shadow-[0_50px_150px_rgba(25,10,4,.45)] backdrop-blur-xl lg:grid-cols-[.9fr_1.1fr]"><div className="hidden bg-[url('/social-preview.jpg')] bg-cover bg-center p-10 text-white lg:flex lg:flex-col lg:justify-end"><p className="text-[10px] uppercase tracking-[.5em]">NØIR membership</p><h1 className="mt-4 font-serif text-6xl leading-[.9]">Your ritual starts here.</h1><p className="mt-5 max-w-sm text-sm leading-7 text-white/75">Save favorites, track orders, get personal recommendations, and unlock the NØIR experience.</p></div><form onSubmit={submit} className="p-7 md:p-12"><div className="grid h-14 w-14 place-items-center rounded-full bg-[#3c2115] text-white"><UserPlus/></div><p className="mt-6 text-[9px] uppercase tracking-[.45em] text-[#9e6745]">Create your account</p><h2 className="mt-3 font-serif text-5xl">Join NØIR.</h2><div className="mt-8 grid gap-4"><input name="name" required minLength={2} placeholder="Full name / الاسم" className="rounded-2xl bg-white/70 px-5 py-4 outline-none ring-[#8c5a3c] focus:ring-2"/><input name="email" type="email" required placeholder="Email" className="rounded-2xl bg-white/70 px-5 py-4 outline-none ring-[#8c5a3c] focus:ring-2"/><input name="phone" placeholder="Phone / رقم الهاتف" className="rounded-2xl bg-white/70 px-5 py-4 outline-none ring-[#8c5a3c] focus:ring-2"/><div className="relative"><input name="password" type={show?'text':'password'} required minLength={8} placeholder="Password (8+ characters)" className="w-full rounded-2xl bg-white/70 px-5 py-4 pr-12 outline-none ring-[#8c5a3c] focus:ring-2"/><button type="button" onClick={()=>setShow(v=>!v)} className="absolute right-4 top-1/2 -translate-y-1/2">{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div><select name="language" className="rounded-2xl bg-white/70 px-5 py-4 outline-none"><option value="en">English</option><option value="ar">العربية</option></select><div><input name="adminCode" type="password" placeholder="Admin access code (owner only)" className="w-full rounded-2xl border border-[#9c6848]/20 bg-white/45 px-5 py-4 outline-none"/><p className="mt-2 text-[11px] text-[#77513c]">Leave blank for a customer account. Use the ADMIN_PASSWORD value to create the owner account.</p></div></div>{error&&<p className="mt-4 rounded-2xl bg-red-100 p-3 text-sm text-red-800">{error}</p>}<button disabled={loading} className="mt-6 w-full rounded-full bg-[#3c2115] px-6 py-4 text-white disabled:opacity-50">{loading?'Creating account...':'Create account'}</button><p className="mt-5 text-center text-sm">Already a member? <a className="font-semibold underline" href="/login">Log in</a></p></form></div></section><Footer/></main>
}
